[features]
seeds = false
skip-lint = false
[programs.devnet]
first = "8UnyHmgUpSfryGMHMPWFxsiNRmDew9e98sETj4SdK9kW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/usman/.config/solana/devnet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
